# MoveIt uses this configuration for controller management
# MoveItSimpleControllerManager 和 MoveItRos2ControllerManager
moveit_controller_manager: moveit_simple_controller_manager/MoveItRos2ControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: follow_joint_trajectory
    default: true