# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_ros2_controller_manager/MoveItRos2ControllerManager

ros2_controller: 
  type: FollowJointTrajectory
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
  action_ns: follow_joint_trajectory
  default: true